### PR TITLE
added timestamp as title attribute in header across all the pages

### PR DESCRIPTION
**Pull request by ibkay998**

### CODE REVIEW

**Comment by sgnilreutr** [comment]
@ibkay998 
Screenshot 2022-10-11 at 18 52 05
Please be more careful with this. Please update your code, you should have warnings on it, or do you not get them?

**Comment by ibkay998** [comment]
sorry about that will make the changes.

**Comment by sgnilreutr** [comment]
@ibkay998 I also highly recommend/request you to rewrite your code to be:
1. Using one file that is imported in the headers, giving that the logic is always the same.
2. That you do not use the `let` construction here, but rather make it all a function that returns something. And you will use that function inline on the 'title' attribute, as such: 'title={getEmailListTimestamp()}'

**Comment by ibkay998** [comment]
noted will get right on that thanks

**Comment by sgnilreutr** [comment]
Closes #823

**Pull request merged**
